"use client";

import { useState, useEffect, useMemo } from "react";
import { cn } from "@/lib/utils";
import { ImageIcon, Loader2 } from "lucide-react";

interface MarkdownImageProps {
  src?: string | Blob;
  alt?: string;
  title?: string;
  onClick?: (src: string) => void;
  baseUrl?: string;
}

export function MarkdownImage({
  src,
  alt = "",
  title,
  onClick,
  baseUrl = "",
}: MarkdownImageProps) {
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(false);

  // 1. Handle Blob vs String and URL generation
  const displaySrc = useMemo(() => {
    if (!src) return "";

    if (src instanceof Blob) {
      return URL.createObjectURL(src);
    }

    // Handle relative URLs for strings
    const isAbsolute =
      src.startsWith("http") || src.startsWith("/") || src.startsWith("data:");
    return isAbsolute ? src : `${baseUrl}${src}`;
  }, [src, baseUrl]);

  // 2. Clean up Blob URLs to prevent memory leaks
  useEffect(() => {
    return () => {
      if (displaySrc.startsWith("blob:")) {
        URL.revokeObjectURL(displaySrc);
      }
    };
  }, [displaySrc]);

  if (!src) return null;

  const handleClick = () => {
    if (onClick) onClick(displaySrc);
  };

  // Error State: Uses span/em to stay valid inside <p> tags if necessary,
  // though figure is used here as a block-level fallback.
  if (error) {
    return (
      <span className="my-6 bg-muted/30 rounded-lg border border-dashed border-border p-8 block">
        <ImageIcon className="h-12 w-12 text-muted-foreground/50" />
        <span className="text-center">
          <span className="text-sm font-medium text-muted-foreground block">
            Failed to load image
          </span>
          {alt && (
            <span className="text-xs text-muted-foreground/70 mt-1 block">
              {alt}
            </span>
          )}
        </span>
      </span>
    );
  }

  return (
    /* We use 'span' with 'display: block' instead of 'figure' to ensure 
       it is legally nestable inside <p> tags often generated by Markdown parsers. */
    <span className="my-6 group block">
      <span
        className={cn(
          "relative overflow-hidden rounded-lg border border-border bg-muted/30 block",
          "transition-all duration-200",
          onClick && "cursor-pointer hover:border-primary/50 hover:shadow-lg",
          isLoading && "min-h-50",
        )}
        onClick={handleClick}
        role={onClick ? "button" : undefined}
        tabIndex={onClick ? 0 : undefined}
        onKeyDown={
          onClick
            ? (e) => {
                if (e.key === "Enter" || e.key === " ") {
                  e.preventDefault();
                  handleClick();
                }
              }
            : undefined
        }
      >
        {/* Loading spinner */}
        {isLoading && (
          <span className="absolute inset-0 flex items-center justify-center bg-muted/50">
            <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
          </span>
        )}

        {/* Image */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={displaySrc}
          alt={alt}
          title={title}
          onLoad={() => setIsLoading(false)}
          onError={() => {
            setIsLoading(false);
            setError(true);
          }}
          className={cn(
            "w-full h-auto transition-opacity duration-300 block",
            isLoading ? "opacity-0" : "opacity-100",
          )}
          loading="lazy"
        />

        {/* Zoom indicator */}
        {onClick && !isLoading && (
          <span className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors duration-200 flex items-center justify-center">
            <span className="opacity-0 group-hover:opacity-100 transition-opacity duration-200 bg-black/70 text-white px-3 py-1.5 rounded-md text-sm font-medium">
              Click to expand
            </span>
          </span>
        )}
      </span>

      {/* Caption */}
      {(alt || title) && !error && (
        <span className="mt-3 text-center text-sm text-muted-foreground px-2 block italic">
          {title || alt}
        </span>
      )}
    </span>
  );
}

export default MarkdownImage;
