name: Deploy to Staging
on:
  push:
    branches: [staging]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to ProISP
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ./out/
          remote_path: ${{ secrets.SSH_PATH }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          args: --exclude '.well-known/' --exclude 'cgi-bin/'
